export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_STARTED = 'GET_QUESTIONS_STARTED';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const EMPTY_QUESTIONS = 'EMPTY_QUESTIONS';